# docker-compose.yml
version: "2.4"

volumes:
  db_data:

services:
  mysql:
    platform: linux/amd64
    build:
      context: ./db/
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  ed-bg-activities:
    container_name: ed-bg-activities
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        - NPM_TOKEN=$NPM_TOKEN
    ports:
      - 8080:8080
    environment:
      - ENVIRONMENT=yap-local
      - MICROSERVICE_NAME=
      - MICROSERVICE_TYPE=com.yapsody.event-discovery-bg-activity
      - MICROSERVICE_IP=0.0.0.0
      - APP_HOST=0.0.0.0
      - APP_PORT=8180
      - SWAGGER_PORT=8180
      - MYSQL_HOST=mysql
      - MYSQL_USERNAME=user
      - MYSQL_PASSWORD=secret
      - MYSQL_DB_NAME=event_discovery
    volumes:
      - .:/app:delegated
      - ./:/home/node/app
