name: Sentry Release

on:
  workflow_run:
    workflows: ["Build"]
    branches: [master]
    types:
      - completed

jobs:

  sentry-release:
    name: Create Sentry release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: yapsody/actions/.github/workflows/sentry-release.yml@master
    secrets: inherit
